apiVersion: v1
kind: Service
metadata:
  name: prsp
spec:
  type: ClusterIP
  selector:
    app: prsp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prsp
  labels:
    app: prsp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prsp
  template:
    metadata:
      labels:
        app: prsp
    spec:
      containers:
        - name: prsp
          image: frizer/prsp
          imagePullPolicy: Always
          ports:
            - name: liveness-port
              containerPort: 8080
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_DB
            - name: DB_CONNECTION
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@service-postgres.default.svc.cluster.local:5432/$(POSTGRES_DB)"
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
